
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'C\x11b\x82\xc8z\xaa\xe5t|\x11\xd7g#\xa2\xd0'
    
_lr_action_items = {'COMMENT':([0,3,8,10,11,13,14,15,16,18,19,21,27,29,30,31,33,34,],[2,2,-9,-24,-13,-15,-14,-10,-23,-22,-16,-21,-11,-17,-18,-19,-20,-12,]),')':([10,26,28,],[-24,31,33,]),'INT':([8,12,22,24,25,32,],[18,21,18,18,18,18,]),'-':([8,19,22,24,25,32,],[12,25,12,12,12,12,]),'+':([19,],[24,]),'REGISTER':([8,20,22,23,24,25,32,],[10,10,10,10,10,10,10,]),'HEX':([8,22,24,25,32,],[16,16,16,16,16,]),',':([10,11,13,14,15,16,18,19,21,27,29,30,31,33,],[-24,-13,-15,-14,22,-23,-22,-16,-21,32,-17,-18,-19,-20,]),'RAW':([0,],[6,]),'(':([11,18,19,21,],[20,-22,23,-21,]),':':([8,],[17,]),'ID':([0,8,22,24,25,32,],[8,19,19,19,19,19,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,21,27,29,30,31,33,34,],[-3,-8,-4,0,-2,-6,-1,-9,-5,-24,-13,-15,-14,-10,-23,-7,-22,-16,-21,-11,-17,-18,-19,-20,-12,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comment':([0,3,],[1,9,]),'instr':([0,],[3,]),'int':([8,22,24,25,32,],[11,11,11,11,11,]),'expr':([0,],[4,]),'register':([8,20,22,23,24,25,32,],[13,26,13,28,13,13,13,]),'hex':([8,22,24,25,32,],[14,14,14,14,14,]),'label':([0,],[5,]),'raw':([0,],[7,]),'arg':([8,22,24,25,32,],[15,27,29,30,34,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> raw','expr',1,'p_expr','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',20),
  ('expr -> label','expr',1,'p_expr','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',21),
  ('expr -> comment','expr',1,'p_expr','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',22),
  ('expr -> instr','expr',1,'p_expr','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',23),
  ('expr -> instr comment','expr',2,'p_expr','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',24),
  ('raw -> RAW','raw',1,'p_raw','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',30),
  ('label -> ID :','label',2,'p_label','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',35),
  ('comment -> COMMENT','comment',1,'p_comment','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',40),
  ('instr -> ID','instr',1,'p_instr_no_arg','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',46),
  ('instr -> ID arg','instr',2,'p_instr_one_arg','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',51),
  ('instr -> ID arg , arg','instr',4,'p_instr_two_arg','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',56),
  ('instr -> ID arg , arg , arg','instr',6,'p_instr_three_arg','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',61),
  ('arg -> int','arg',1,'p_arg','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',68),
  ('arg -> hex','arg',1,'p_arg','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',69),
  ('arg -> register','arg',1,'p_arg','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',70),
  ('arg -> ID','arg',1,'p_arg','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',71),
  ('arg -> ID + arg','arg',3,'p_arg_ext','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',77),
  ('arg -> ID - arg','arg',3,'p_arg_ext','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',78),
  ('arg -> int ( register )','arg',4,'p_arg_brackets','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',84),
  ('arg -> ID ( register )','arg',4,'p_arg_brackets','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',85),
  ('int -> - INT','int',2,'p_int_minus','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',91),
  ('int -> INT','int',1,'p_int','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',95),
  ('hex -> HEX','hex',1,'p_hex','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',100),
  ('register -> REGISTER','register',1,'p_register','/home/jzuiddam/documents/uva/inf/compbox/src/asmyacc.py',105),
]
