#!/bin/bash     
# Compileer *.s.opt en simuleer.
ssh sremote.science.uva.nl "cd compbox/benchmarks/opt; for file in *.s.opt; do mv \$file `basename \$file .s.opt`.s; done; make; for f in acron clinpack dhrystone pi slalom whet; do ./\$f.sh; cat \$f.cycles | grep 'sim_cycle'; done "

